
/* !!! This is code generated by Prisma. Do not edit directly. !!!
/* eslint-disable */

Object.defineProperty(exports, "__esModule", { value: true });

const {
  Decimal,
  objectEnumValues,
  makeStrictEnum,
  Public,
  getRuntime,
  skip
} = require('./runtime/index-browser.js')


const Prisma = {}

exports.Prisma = Prisma
exports.$Enums = {}

/**
 * Prisma Client JS version: 6.9.0
 * Query Engine version: 81e4af48011447c3cc503a190e86995b66d2a28e
 */
Prisma.prismaVersion = {
  client: "6.9.0",
  engine: "81e4af48011447c3cc503a190e86995b66d2a28e"
}

Prisma.PrismaClientKnownRequestError = () => {
  const runtimeName = getRuntime().prettyName;
  throw new Error(`PrismaClientKnownRequestError is unable to run in this browser environment, or has been bundled for the browser (running in ${runtimeName}).
In case this error is unexpected for you, please report it in https://pris.ly/prisma-prisma-bug-report`,
)};
Prisma.PrismaClientUnknownRequestError = () => {
  const runtimeName = getRuntime().prettyName;
  throw new Error(`PrismaClientUnknownRequestError is unable to run in this browser environment, or has been bundled for the browser (running in ${runtimeName}).
In case this error is unexpected for you, please report it in https://pris.ly/prisma-prisma-bug-report`,
)}
Prisma.PrismaClientRustPanicError = () => {
  const runtimeName = getRuntime().prettyName;
  throw new Error(`PrismaClientRustPanicError is unable to run in this browser environment, or has been bundled for the browser (running in ${runtimeName}).
In case this error is unexpected for you, please report it in https://pris.ly/prisma-prisma-bug-report`,
)}
Prisma.PrismaClientInitializationError = () => {
  const runtimeName = getRuntime().prettyName;
  throw new Error(`PrismaClientInitializationError is unable to run in this browser environment, or has been bundled for the browser (running in ${runtimeName}).
In case this error is unexpected for you, please report it in https://pris.ly/prisma-prisma-bug-report`,
)}
Prisma.PrismaClientValidationError = () => {
  const runtimeName = getRuntime().prettyName;
  throw new Error(`PrismaClientValidationError is unable to run in this browser environment, or has been bundled for the browser (running in ${runtimeName}).
In case this error is unexpected for you, please report it in https://pris.ly/prisma-prisma-bug-report`,
)}
Prisma.Decimal = Decimal

/**
 * Re-export of sql-template-tag
 */
Prisma.sql = () => {
  const runtimeName = getRuntime().prettyName;
  throw new Error(`sqltag is unable to run in this browser environment, or has been bundled for the browser (running in ${runtimeName}).
In case this error is unexpected for you, please report it in https://pris.ly/prisma-prisma-bug-report`,
)}
Prisma.empty = () => {
  const runtimeName = getRuntime().prettyName;
  throw new Error(`empty is unable to run in this browser environment, or has been bundled for the browser (running in ${runtimeName}).
In case this error is unexpected for you, please report it in https://pris.ly/prisma-prisma-bug-report`,
)}
Prisma.join = () => {
  const runtimeName = getRuntime().prettyName;
  throw new Error(`join is unable to run in this browser environment, or has been bundled for the browser (running in ${runtimeName}).
In case this error is unexpected for you, please report it in https://pris.ly/prisma-prisma-bug-report`,
)}
Prisma.raw = () => {
  const runtimeName = getRuntime().prettyName;
  throw new Error(`raw is unable to run in this browser environment, or has been bundled for the browser (running in ${runtimeName}).
In case this error is unexpected for you, please report it in https://pris.ly/prisma-prisma-bug-report`,
)}
Prisma.validator = Public.validator

/**
* Extensions
*/
Prisma.getExtensionContext = () => {
  const runtimeName = getRuntime().prettyName;
  throw new Error(`Extensions.getExtensionContext is unable to run in this browser environment, or has been bundled for the browser (running in ${runtimeName}).
In case this error is unexpected for you, please report it in https://pris.ly/prisma-prisma-bug-report`,
)}
Prisma.defineExtension = () => {
  const runtimeName = getRuntime().prettyName;
  throw new Error(`Extensions.defineExtension is unable to run in this browser environment, or has been bundled for the browser (running in ${runtimeName}).
In case this error is unexpected for you, please report it in https://pris.ly/prisma-prisma-bug-report`,
)}

/**
 * Shorthand utilities for JSON filtering
 */
Prisma.DbNull = objectEnumValues.instances.DbNull
Prisma.JsonNull = objectEnumValues.instances.JsonNull
Prisma.AnyNull = objectEnumValues.instances.AnyNull

Prisma.NullTypes = {
  DbNull: objectEnumValues.classes.DbNull,
  JsonNull: objectEnumValues.classes.JsonNull,
  AnyNull: objectEnumValues.classes.AnyNull
}



/**
 * Enums
 */

exports.Prisma.TransactionIsolationLevel = makeStrictEnum({
  ReadUncommitted: 'ReadUncommitted',
  ReadCommitted: 'ReadCommitted',
  RepeatableRead: 'RepeatableRead',
  Serializable: 'Serializable'
});

exports.Prisma.RolesScalarFieldEnum = {
  id: 'id',
  name: 'name',
  detail: 'detail'
};

exports.Prisma.UsersScalarFieldEnum = {
  id: 'id',
  username: 'username',
  password: 'password',
  first_name: 'first_name',
  last_name: 'last_name',
  role_id: 'role_id',
  email: 'email',
  disable: 'disable',
  created_at: 'created_at',
  updated_at: 'updated_at'
};

exports.Prisma.Region_typesScalarFieldEnum = {
  id: 'id',
  name: 'name',
  detail: 'detail'
};

exports.Prisma.RegionsScalarFieldEnum = {
  id: 'id',
  name: 'name',
  detail: 'detail',
  region_type_id: 'region_type_id'
};

exports.Prisma.TemplatesScalarFieldEnum = {
  id: 'id',
  name: 'name',
  image_filename: 'image_filename',
  pdf_filename: 'pdf_filename',
  total_no: 'total_no',
  created_at: 'created_at',
  updated_at: 'updated_at'
};

exports.Prisma.Template_regionsScalarFieldEnum = {
  id: 'id',
  template_id: 'template_id',
  region_id: 'region_id',
  sx: 'sx',
  sy: 'sy',
  ex: 'ex',
  ey: 'ey'
};

exports.Prisma.Template_marker_centersScalarFieldEnum = {
  template_region_id: 'template_region_id',
  x: 'x',
  y: 'y'
};

exports.Prisma.AnswersScalarFieldEnum = {
  id: 'id',
  name: 'name',
  owner_id: 'owner_id',
  subject: 'subject',
  year: 'year',
  term: 'term',
  total_no: 'total_no',
  shared: 'shared',
  disable: 'disable',
  created_at: 'created_at',
  updated_at: 'updated_at'
};

exports.Prisma.Answer_detailsScalarFieldEnum = {
  id: 'id',
  answer_id: 'answer_id',
  no: 'no',
  point: 'point',
  correct_all: 'correct_all',
  choice_correct: 'choice_correct'
};

exports.Prisma.GroupsScalarFieldEnum = {
  id: 'id',
  name: 'name',
  subject: 'subject',
  year: 'year',
  term: 'term',
  owner_id: 'owner_id',
  template_id: 'template_id',
  answer_id: 'answer_id',
  disable: 'disable',
  created_at: 'created_at',
  updated_at: 'updated_at'
};

exports.Prisma.Sheet_statusesScalarFieldEnum = {
  id: 'id',
  name: 'name',
  detail: 'detail'
};

exports.Prisma.SheetsScalarFieldEnum = {
  id: 'id',
  original_name: 'original_name',
  image_filename: 'image_filename',
  group_id: 'group_id',
  total_scores: 'total_scores',
  sheet_status_id: 'sheet_status_id',
  process_id: 'process_id',
  marker_tl_center: 'marker_tl_center',
  marker_tr_center: 'marker_tr_center',
  marker_bl_center: 'marker_bl_center',
  marker_br_center: 'marker_br_center',
  predict_ans_detail: 'predict_ans_detail',
  predict_ans_result: 'predict_ans_result',
  predict_std_fill_detail: 'predict_std_fill_detail',
  predict_std_fill_result: 'predict_std_fill_result',
  created_at: 'created_at',
  updated_at: 'updated_at'
};

exports.Prisma.Cross_typesScalarFieldEnum = {
  id: 'id',
  name: 'name',
  detail: 'detail'
};

exports.Prisma.SortOrder = {
  asc: 'asc',
  desc: 'desc'
};

exports.Prisma.NullableJsonNullValueInput = {
  DbNull: Prisma.DbNull,
  JsonNull: Prisma.JsonNull
};

exports.Prisma.JsonNullValueInput = {
  JsonNull: Prisma.JsonNull
};

exports.Prisma.QueryMode = {
  default: 'default',
  insensitive: 'insensitive'
};

exports.Prisma.NullsOrder = {
  first: 'first',
  last: 'last'
};

exports.Prisma.JsonNullValueFilter = {
  DbNull: Prisma.DbNull,
  JsonNull: Prisma.JsonNull,
  AnyNull: Prisma.AnyNull
};


exports.Prisma.ModelName = {
  roles: 'roles',
  users: 'users',
  region_types: 'region_types',
  regions: 'regions',
  templates: 'templates',
  template_regions: 'template_regions',
  template_marker_centers: 'template_marker_centers',
  answers: 'answers',
  answer_details: 'answer_details',
  groups: 'groups',
  sheet_statuses: 'sheet_statuses',
  sheets: 'sheets',
  cross_types: 'cross_types'
};

/**
 * This is a stub Prisma Client that will error at runtime if called.
 */
class PrismaClient {
  constructor() {
    return new Proxy(this, {
      get(target, prop) {
        let message
        const runtime = getRuntime()
        if (runtime.isEdge) {
          message = `PrismaClient is not configured to run in ${runtime.prettyName}. In order to run Prisma Client on edge runtime, either:
- Use Prisma Accelerate: https://pris.ly/d/accelerate
- Use Driver Adapters: https://pris.ly/d/driver-adapters
`;
        } else {
          message = 'PrismaClient is unable to run in this browser environment, or has been bundled for the browser (running in `' + runtime.prettyName + '`).'
        }

        message += `
If this is unexpected, please open an issue: https://pris.ly/prisma-prisma-bug-report`

        throw new Error(message)
      }
    })
  }
}

exports.PrismaClient = PrismaClient

Object.assign(exports, Prisma)
